gemini_columns = ['encounter_id', 'subject_id', 'city', 'province', 'country', 'language',
    'total_direct_cost', 'total_indirect_cost', 'total_cost', 'hospital_id',
    'sex', 'age', 'admit_timestamp', 'discharge_timestamp',
    'admit_category', 'discharge_disposition', 'responsibility_for_payment',
    'province_territory_issuing_health_card_number', 'number_of_alc_days',
    'institution_from', 'institution_from_type', 'institution_to',
    'institution_to_type', 'readmission', 'residence_code',
    'admitting_service_raw', 'discharging_service_raw', 'mrp_service',
    'cmg', 'admitting_physician', 'discharging_physician', 'mrp',
    'admitting_physician_gim', 'discharging_physician_gim', 'mrp_gim',
    'admitting_service_mapped', 'discharging_service_mapped',
    'from_nursing_home_mapped', 'from_acute_care_institution_mapped',
    'los_derived', 'del_present', 'gemini_cohort', 'discharge_description',
    'admit_via_ambulance', 'triage_level',
    'physician_initial_assessment_date_time', 'er_admit_timestamp',
    'disposition_date_time', 'er_discharge_timestamp',
    'length_of_stay_in_er', 'mortality']