dataset:
  name: nihcxr
  object: drift_detection.datasets.NIHCXRDataset
  cfg_path: drift_detection/datasets/configs/nihcxr.yaml

shift: synthetic_shift_gaussian

reductor:
  dr_method: TAE_txrv_CNN
  # batch_size: 64
  # num_workers: 4

tester:
  type: TSTester
  tester_method: mmd
  backend: pytorch
  n_permutations: 1
  device: None

detector:
  p_val_threshold: 0.05

shiftapplicator:
  type: SyntheticShiftApplicator
  shift_type: gn_shift

experimenter:
  experiment_type: sensitivity_test

results_path: ./results.pickle
