model__input_dim: null
model__hidden_dims: [256, 256, 256, 256]
model__layer_dim: 2
model__output_dim: 1
model__activation: 'ReLU'
criterion: 'BCEWithLogitsLoss'
optimizer: 'Adagrad'
optimizer__weight_decay: 1.e-6
activation: 'Sigmoid'
lr_scheduler: 'StepLR'
lr_scheduler__gamma: 0.5
lr_scheduler__step_size: 128
lr_update_per_batch: True
lr: 2.e-3
batch_size: 64
max_epochs: 256
reweight: "mini-batch"
train_loader__num_workers: 2
train_loader__shuffle: True
train_loader__pin_memory: True
test_loader__num_workers: 2
test_loader__shuffle: False
test_loader__pin_memory: True
