service: service:svc
include:
  - /model_repo
  - /*.py
exclude:
  - /__pycache__
python:
  packages:
  - bentoml[triton]==1.2.0
  - tritonclient[all]==2.41.0
  - torchxrayvision==1.2.1
docker:
  base_image: nvcr.io/nvidia/tritonserver:24.01-py3
