---
# Gemini database parameters, required if running extraction from database.
dbms: "postgresql"
port: 5432
host: "db.gemini-hpc.ca"
database: "delirium_v3_0_0"

output_folder: "./_extract"

# Extract data from years.
years: []
# Extract data from hospital sites.
hospitals: []

# yyyy-mm-dd. Select starting from filter_date_from to filter_date_to.
from_date: ""
to_date: ""
