---
# MIMIC database parameters, required if running extraction from database.
dbms: "postgresql"
port: 5432
host: "localhost"
database: "mimiciv"

output_folder: "./_extract"

# Extract data from years.
years: []
# Extract data from hospital sites.
hospitals: []
# yyyy-mm-dd. Select starting from from_date and/or to_date.
from_date: ""
to_date: ""
