name: Documentation and Coverage Report

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docs.yml
      - '**.py'
      - poetry.lock
      - pyproject.toml
      - requirements.txt
      - '**.rst'
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/docs.yml
      - '**.py'
      - poetry.lock
      - pyproject.toml
      - requirements.txt
      - '**.rst'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: sudo apt-get install libcurl4-openssl-dev libssl-dev
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8.5
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Build docs and coverage report
        run: |
          cd docs && make html
          cd .. && coverage run -m pytest && coverage html && cp htmlcov/* docs/build/html/_static/
          mv docs/build/html/_static/index.html docs/build/html/_static/coverage_report.html
      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: github_pages
          folder: docs/build/html
