name: Static code analysis

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/static_code_analysis.yml
      - '**.py'
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/static_code_analysis.yml
      - '**.py'

jobs:
  run-code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: sudo apt-get install libcurl4-openssl-dev libssl-dev
      - uses: actions/checkout@v3
        with:
          python-version: 3.8.5
          cache: 'poetry'
      - name: Create virtual environment, install dependencies and run tests
        run: |
          python3 -m venv venv && source venv/bin/activate
          pip install --upgrade pip && pip install poetry && poetry install
      - name: Check code
        uses: pre-commit/action@v2.0.3
