name: Unit-tests

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/unittest.yml
      - '**.py'
      - poetry.lock
      - pyproject.toml
      - requirements.txt
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/unittest.yml
      - '**.py'
      - poetry.lock
      - pyproject.toml
      - requirements.txt

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt dependencies
        run: sudo apt-get install libcurl4-openssl-dev libssl-dev
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8.5
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Run unit tests
        run: python3 -m pytest tests/
